# Generated by Django 6.0.3 on 2026-03-20 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_number', models.IntegerField()),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.CharField(max_length=100)),
                ('visit_type', models.CharField(default='Paid', max_length=20)),
                ('referred_by', models.CharField(blank=True, max_length=100)),
                ('payment_mode', models.CharField(blank=True, max_length=20)),
                ('total_amount', models.FloatField(default=0)),
                ('paid_amount', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('diagnosis', models.TextField()),
                ('medicines', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
    ]
