# Generated by Django 6.0.3 on 2026-03-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='referred_by',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visit_type',
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.CharField(default='Doctor', max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
