# Generated by Django 6.0.3 on 2026-03-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_visit_balance_remove_visit_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pharmacy', 'Pharmacy'), ('non_medical', 'Non Medical'), ('lab', 'Lab'), ('doctor', 'Doctor Visit'), ('room', 'Room Facility')], max_length=20)),
                ('date', models.DateField()),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('amount', models.IntegerField()),
                ('paid_amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
    ]
