# Generated by Django 6.0.3 on 2026-03-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_billing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='sex',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
