# Generated by Django 6.0.3 on 2026-03-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_sex_patient_gender_remove_billing_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='category',
            field=models.CharField(choices=[('pharmacy', 'Pharmacy materials'), ('non_medical', 'Non Medical Items'), ('lab', 'Lab Investigation'), ('doctor', 'Doctor Visits'), ('room', 'Room Facility')], max_length=20),
        ),
    ]
