# Generated by Django 6.0.3 on 2026-03-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_billing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='category',
            field=models.CharField(choices=[('pharmacy', 'Pharmacy materials'), ('no_medical', 'Non Medical Items'), ('lab', 'Lab Investigation'), ('doctor', 'Doctor Visits'), ('room', 'Room Facility')], max_length=20),
        ),
    ]
