# Generated by Django 6.0.3 on 2026-03-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_billing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
