# Generated by Django 6.0.3 on 2026-03-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_billing_from_date_billing_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='doa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
